### ISSUE TITLE
Neocities doesn't say the updates

### ISSUE THREAD

**Issue by ReduxFlakes** [bcomnes/deploy-to-neocities#124]
So, when I deployed my website to Neocities I noticed that when I go to my website Neocities page it doesn't say that the website was updated for some reason, if I manually edit the files in Neocities then it says what files were updated. Is this supposed to happen and/or can it be fixed? I'm using the stable (v1) branch.

repo: https://github.com/ReduxFlakes/eversoul

Thanks!

**Comment by bcomnes** [comment]
Only time I've not seen updates is due to cache issues. Have you tried clearing your cache after updates? Otherwise, maybe something about your build is not updating the way you expect? This tool only uploads files that changed in some way as well, based on a content hash. A content hash collision is extremely rare.

**Comment by ReduxFlakes** [comment]
Oh you are right, clearing the browser's cache shows the last update was 1 minute ago, thanks!
