### ISSUE TITLE
consider adding a “cleanup exceptions” option

### ISSUE THREAD

**Issue by zamfofex** [bcomnes/deploy-to-neocities#28]
Hello again! :wave:

I have recently decided to stop using MongoDB as a source of data for my Neocities website, instead storing the (quite simple) data on Neocities itself.

I decided to dedicate a specific directory on Neocities for the data that I would then use to build each deployment. It seems to have worked fine (the first time), but now my data directory was deleted from Neocities! (Which is fine since I have a backup.)

The problem is that I set the `cleanup` flag to `true`, so that unused old files would get deleted automatically. It is important to me that the files are cleaned up, because I am (~~very undecisevely~~) always moving files around, and I don’t want for old versions of files to hang around.

I was wondering if it’d be possible to provide an option for specific directories (or maybe a Unix‐like glob) to not be cleaned up even when `cleanup` is set to true. Something like `cleanup-exceptions`.

I saw that you actually have another repository (`async-neocities`), where you keep most of the code regarding deployment. Maybe it would make more sense to actually move this issue there? It’s up to you, of course!

Thanks in advance for the attention!

**Comment by bcomnes** [comment]
Yeah good idea.  I'm a little on the fence adding to much sophistication here, because of the danger of deleting data that people might care about.  

If we add a `cleanup-exceptions` glob string, I see the following changes (in some form) would be necessary:

 - A verbose preview mode.  This would print out all the files that are cleanup protected (never deleted) and maybe other info about what needs updating and deleting/ignored.  This way one could set a cleanup-exception glob, and preview what it will do before turning cleanup on.

This functionality would need to live in async-neocities and exposed in the action. 

I would be willing to add this soonish, unless anyone else want to try to add something.

**Comment by bcomnes** [comment]
For one, I would like this feature because it would enable me to have a folder on a website that I could throw loose files into that I want to send to other people, without having to create another website.

**Comment by zamfofex** [comment]
> But just on a note on best practice here: if you care about something, it should be saved in git. […] If you have more detail on the issue you are running into I would be happy to advise on the use case.

As I said, I was moving those files from a database, so the use‐case is very similar to that of a database in general. As you might know, I used my website to store fictional stories I occasionally write (mostly fanfiction). In my particular case, I had two uses for the data files:

- I prefer to store the actual stories on the data directory, so that I can update them independently of the actual infrastructure of the website.
- I store the feedback messages people leave on the stories on the website on the data directory, so I can load them from the browser using scripts.

Regarding the first one, I use those data on deployment, so I would need to redeploy to actually consolidate the changes from the Markdown data files to the actual website. Note that I think this is fine, given that I don’t frequently actually update the stories anyway.

Regarding the second one, note that it is user‐generated content that really doesn’t make sense to be stored in Git. I set up a Vercel Function API backend to update the fies on Neocities (previously MongoDB) whenever someone clicks to share a feedback message.

**Comment by bcomnes** [comment]
Yeah that makes sense.  +1

**Comment by bcomnes** [comment]
Putting this into my todo queue

**Comment by bcomnes** [comment]
Ok v1.1.0 has a `protected_files` input that accepts a [minimatch](http://ghub.io/minimatch) glob string that will protect files from being cleaned up that match the glob string.  

Please use caution with it at first since I've only tested it in a few cases.  (e.g. have data backups, and test with cleanup false to make sure your glob string is matching correctly.)

let me know how it goes!

**Comment by zamfofex** [comment]
Hello. Thank you for having worked on this! :tada: It seems to be working perfectly for me!

I won’t be careless, though, I’ll keep backups. Although, I honestly doubt I’ll actually need them!

**Comment by bcomnes** [comment]
One thing I did notice is that cleanup isn't cleaning up empty directories. I made an issue to look into that soon as well.
